export const hour = 19;
export const urlGDPR = 'https://freeroom.es/srcapp/demo/eeg9EUa2cMZo4Qo9Bm6pIpMNg/rgpd.html';
export const dns = 'http://freeroom.eu-west-3.elasticbeanstalk.com';

export const districts = [
    {
      "codigo": "08001",
      "name": "",
      "city": "Barcelona",
    },    
    {
      "codigo": "08002",
      "name": "Ciutat Vella",
      "city": "Barcelona",
    },    
    {
      "codigo": "08003",
      "name": "Ciutat Vella",
      "city": "Barcelona",
    },    
    {
      "codigo": "08004",
      "name": "Sants-Montjuïc",
      "city": "Barcelona",
    },    
    {
      "codigo": "08005",
      "name": "Sant Martí",
      "city": "Barcelona",
    },    
    {
      "codigo": "08006",
      "name": "",
      "city": "Barcelona",
    },    
    {
      "codigo": "08007",
      "name": "",
      "city": "Barcelona",
    },    
    {
      "codigo": "08008",
      "name": "",
      "city": "Barcelona",
    },    
    {
      "codigo": "08009",
      "name": "Eixample",
      "city": "Barcelona",
    },    
    {
      "codigo": "08010",
      "name": "Eixample",
      "city": "Barcelona",
    },    
    {
      "codigo": "08011",
      "name": "Eixample",
      "city": "Barcelona",
    },
    {
      "codigo": "08012",
      "name": "Gràcia i Park Güell",
      "city": "Barcelona",
    },
    {
      "codigo": "08013",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08014",
      "name": "Sants-Montjuïc",
      "city": "Barcelona",
    },
    {
      "codigo": "08015",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08016",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08017",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08018",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08019",
      "name": "Sant Martí",
      "city": "Barcelona",
    },
    {
      "codigo": "08020",
      "name": "Sant Martí",
      "city": "Barcelona",
    },
    {
      "codigo": "08021",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08022",
      "name": "Sarrià-St. Gervasi",
      "city": "Barcelona",
    },
    {
      "codigo": "08023",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08024",
      "name": "Gràcia i Park Güell",
      "city": "Barcelona",
    },
    {
      "codigo": "08025",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08026",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08027",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08028",
      "name": "Les Corts y Pedralbes",
      "city": "Barcelona",
    },
    {
      "codigo": "08029",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08030",
      "name": "Sant Andreu",
      "city": "Barcelona",
    },
    {
      "codigo": "08031",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08032",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08033",
      "name": "Nou Barris",
      "city": "Barcelona",
    },
    {
      "codigo": "08034",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08035",
      "name": "Sarrià-St. Gervasi",
      "city": "Barcelona",
    },
    {
      "codigo": "08036",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08037",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08038",
      "name": "Sants-Montjuïc",
      "city": "Barcelona",
    },
    {
      "codigo": "08039",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08040",
      "name": "",
      "city": "Barcelona",
    },
    {
      "codigo": "08041",
      "name": "Horta-Guinardó",
      "city": "Barcelona",
    },
    {
      "codigo": "08042",
      "name": "",
      "city": "Barcelona",
    },
];
//User logueado
export const user = [
    {
      "uid": 2,
      "name": "User 2",
    },    
    {    
      "uid": 0,
      "name": "No identificado",
    },
    {
      "uid": 1,
      "name": "User 1",
    },        
];

export const reserva = [
    {
      "id": 1,
      "startDate": "2024-09-11",
      "endDate": "2024-09-12",
      "status": "PENDING",        
      "hotel": {
        "id": 1,
        "name": "Hotel ILUNION Bel Art",
        "description": "Hotel de 1 estrella",
        "addres": "C/ de Lepant, 406, Horta-Guinardó, 08025 Barcelona",
        "latitude": "41.41025873535068",
        "longitude": "2.1695948163258825",
        "phone": "934335440",
        "city": "Barcelona",
      },      
      "user_id": 1,
      "room": {
        "id": 4,
        "name": "Rooms 1",
        "details": "3 personas",
        "number": "1",
        "price": "150.00",
        "type": "Grande",
        "image1": "https://content.arquitecturaydiseno.es/medio/2018/05/24/aman-tokyo_dc74e659.jpg"
      }
    }
];

export const hotels = [
  {
    "id": 14267,
    "name": "HOTUSA",
    "description": "Hotel",
    "rating": "",
    "Nº Reviews": "",
    "Código Plus": "C52C+GR Barcelona",
    "addres": "Carrer de Mallorca, nº 351, 08013 Barcelona",
    "city": "Barcelona",
    "province": "",
    "website": "hotusahotels.com",
    "phone": "902 27 01 27",
    "email": "agencias@hotusa.es",
    "latitude": 41.4013142,
    "longitude": 2.1720584,
    "rooms": [{
          "id": 1,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,        
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 38004,
    "name": "Camping Masnou",
    "description": "Camping",
    "rating": "3,2",
    "Nº Reviews": 755,
    "Código Plus": "F8G3+4H Barcelona",
    "addres": "Carrer Camil Fabra, 33, 08320 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "campingmasnoubarcelona.com",
    "phone": "935 55 15 03",
    "email": "informacion@campingmasnoubarcelona.com",
    "latitude": 41.4753526,
    "longitude": 2.3039612,
    "rooms": [{
          "id": 2,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "105",
          "onSale": 1,
          "price": "125.00",
          "type": "Cama Doble",
          "image1": "https://phantom-expansion.unidadeditorial.es/a70fc47435328663094136460ba994c2/crop/80x0/942x575/resize/414/f/jpg/assets/multimedia/imagenes/2021/04/09/16179716248641.jpg",
        }]
  },
  {
    "id": 38018,
    "name": "Bed and Bike Hostel",
    "description": "Hotel de 2 estrellas",
    "rating": "4,5",
    "Nº Reviews": 271,
    "Código Plus": "95WG+VF Barcelona",
    "addres": "Carrer de la Diputació, 360, 08013 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "barcelonabedandbike.com",
    "phone": "933 15 87 21",
    "email": "info@barcelonabedandbike.com",
    "latitude": 41.3971332,
    "longitude": 2.1762118,
    "rooms": [{
          "id": 3,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "100",
          "onSale": 1,
          "price": "120.00",
          "type": "Cama Doble",
          "image1": "https://phantom-expansion.unidadeditorial.es/a70fc47435328663094136460ba994c2/crop/80x0/942x575/resize/414/f/jpg/assets/multimedia/imagenes/2021/04/09/16179716248641.jpg",
        }]
  },
  {
    "id": 38019,
    "name": "Hotel Ibis Barcelona Centro (Sagrada Familia)",
    "description": "Hotel de 2 estrellas",
    "rating": "4,3",
    "Nº Reviews": 984,
    "Código Plus": "C52C+8X Barcelona",
    "addres": "Carrer de Nàpols, 230, 232, 08013 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "all.accor.com",
    "phone": "932 08 05 36",
    "email": "-",
    "latitude": 41.4008077,
    "longitude": 2.1724679,
    "rooms": [{
          "id": 4,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "65",
          "onSale": 1,
          "price": "85.00",
          "type": "Cama Sencilla",
          "image1": "https://phantom-expansion.unidadeditorial.es/a70fc47435328663094136460ba994c2/crop/80x0/942x575/resize/414/f/jpg/assets/multimedia/imagenes/2021/04/09/16179716248641.jpg",
        },
        {
          "id": 90,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "95",
          "onSale": 1,
          "price": "105.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        },
        {
          "id": 91,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "115",
          "onSale": 1,
          "price": "135.00",
          "type": "Cama Sencilla y Cama Doble",
          "image1": "https://phantom-expansion.unidadeditorial.es/a70fc47435328663094136460ba994c2/crop/80x0/942x575/resize/414/f/jpg/assets/multimedia/imagenes/2021/04/09/16179716248641.jpg",
        }]

  },
  {
    "id": 38252,
    "name": "Hotel ibis Styles Barcelona City Bogatell",
    "description": "Hotel de 2 estrellas",
    "rating": "4,3",
    "Nº Reviews": 1.355,
    "Código Plus": "95VV+W9 Barcelona",
    "addres": "Carrer de Llull, 71, 08005 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "all.accor.com",
    "phone": "934 83 37 48",
    "email": "-",
    "latitude": 41.3947665,
    "longitude": 2.1934702,
    "rooms": [{
          "id": 5,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "95",
          "onSale": 1,
          "price": "115.00",
          "type": "Cama Sencilla",
          "image1": "https://phantom-expansion.unidadeditorial.es/a70fc47435328663094136460ba994c2/crop/80x0/942x575/resize/414/f/jpg/assets/multimedia/imagenes/2021/04/09/16179716248641.jpg",
        },
        {
          "id": 92,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "125",
          "onSale": 1,
          "price": "145.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 38255,
    "name": "Hotel Catalunya",
    "description": "Hotel de 2 estrellas",
    "rating": "3,8",
    "Nº Reviews": 348,
    "Código Plus": "95PC+5M Barcelona",
    "addres": "Carrer de Santa Anna, 24, 08001 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hcatalunya.com",
    "phone": "933 01 91 50",
    "email": "hcatalunya@hotelcatalunya.net",
    "latitude": 41.3854491,
    "longitude": 2.1717307,
    "rooms": [{
          "id": 6,
          "name": "",
          "details": "",
          "number": "",          
          "availability": 1, 
          "capacity": 0,
          "offerPrice": "90",
          "onSale": 1,
          "price": "110.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        },
        {
          "id": 93,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "125",
          "onSale": 1,
          "price": "145.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 38288,
    "name": "hotel st moritz",
    "description": "Hotel",
    "rating": "4,0",
    "Nº Reviews": 3,
    "Código Plus": "95PC+R2 Barcelona",
    "addres": "Plaça de Catalunya, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "",
    "phone": "",
    "email": "-",
    "latitude": 41.3870154,
    "longitude": 2.1700471,
    "rooms": [{
          "id": 7,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "85",
          "onSale": 1,
          "price": "105.00",
          "type": "Cama Sencilla",
          "image1": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/b0/bd/25/adjoining-room-hotels.jpg?w=1200&h=-1&s=1",
        },
        {
          "id": 94,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "125",
          "onSale": 1,
          "price": "145.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
{
    "id": 38304,
    "name": "Hotel Center Gran Via",
    "description": "Hotel de 1 estrella",
    "rating": "4,4",
    "Nº Reviews": 130,
    "Código Plus": "95P6+2R Barcelona",
    "addres": "Gran Via de les Corts Catalanes, 573, 08011 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "centergranvia.com",
    "phone": "934 51 28 98",
    "email": "info@centergranvia.com",
    "latitude": 41.3850995,
    "longitude": 2.1620724,
    "rooms": [{
          "id": 8,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Sencilla",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        },
        {
          "id": 94,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "125",
          "onSale": 1,
          "price": "145.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 38309,
    "name": "Hotel Ginebra",
    "description": "Hotel de 1 estrella",
    "rating": "4,0",
    "Nº Reviews": 189,
    "Código Plus": "95P9+X6 Barcelona",
    "addres": "Rambla de Catalunya, 1, 08007 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelginebra.com.es",
    "phone": "932 50 20 17",
    "email": "-",
    "latitude": 41.387445,
    "longitude": 2.1680336,
    "rooms": [{
          "id": 9,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 38329,
    "name": "Hostal Dani",
    "description": "Hotel de 1 estrella",
    "rating": "2,4",
    "Nº Reviews": 131,
    "Código Plus": "95M9+VW Barcelona",
    "addres": "Carrer dels Tallers, 9, 08001 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "",
    "phone": "933 02 11 46",
    "email": "-",
    "latitude": 41.3846847,
    "longitude": 2.1697618,
    "rooms": []
  },
  {
    "id": 38341,
    "name": "Hostal Santa Ana",
    "description": "Hotel de 1 estrella",
    "rating": "3,5",
    "Nº Reviews": 144,
    "Código Plus": "95PC+5J Barcelona",
    "addres": "Carrer de Santa Anna, 23, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalsantaanna.com",
    "phone": "933 01 22 46",
    "email": "-",
    "latitude": 41.3854268,
    "longitude": 2.1715839,
    "rooms": [{
          "id": 11,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 38352,
    "name": "Hotel El Call",
    "description": "Hotel de 1 estrella",
    "rating": "3,7",
    "Nº Reviews": 265,
    "Código Plus": "95JG+W7 Barcelona",
    "addres": "Carrer de l&apos;Arc de Sant Ramon del Call, 4, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelelcall.com",
    "phone": "933 02 11 23",
    "email": "hello@hotelelcall.com",
    "latitude": 41.3822614,
    "longitude": 2.1757178,
    "rooms": [{
          "id": 12,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 38369,
    "name": "Berni&apos;s House Bcn",
    "description": "Hotel de 1 estrella",
    "rating": "3,3",
    "Nº Reviews": 205,
    "Código Plus": "95P8+P3 Barcelona",
    "addres": "Gran Via de les Corts Catalanes, 602, 08007 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "bernis-house-bcn.negocio.site",
    "phone": "686 34 28 68",
    "email": "-",
    "latitude": 41.386804,
    "longitude": 2.1652145,
    "rooms": []
  },
  {
    "id": 38373,
    "name": "Hotel Lloret Rambles Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "4,0",
    "Nº Reviews": 832,
    "Código Plus": "95MC+W2 Barcelona",
    "addres": "Rambla de Canaletes, 125, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hlloret.com",
    "phone": "933 17 33 66",
    "email": "info@hlloret.com",
    "latitude": 41.384825,
    "longitude": 2.170102,
    "rooms": [{
          "id": 14,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 38392,
    "name": "Barcelona City Ramblas",
    "description": "Hotel de 1 estrella",
    "rating": "3,5",
    "Nº Reviews": 99,
    "Código Plus": "95P9+3W Barcelona",
    "addres": "La Rambla, 133, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "barcelonacityramblas.com",
    "phone": "934 87 97 62",
    "email": "-",
    "latitude": 41.3851394,
    "longitude": 2.169825,
    "rooms": [{
          "id": 15,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 38420,
    "name": "Hotel Peninsular",
    "description": "Hotel de 1 estrella",
    "rating": "3,4",
    "Nº Reviews": 709,
    "Código Plus": "95HF+R2 Barcelona",
    "addres": "Carrer de Sant Pau, 34, 08001 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelpeninsular.net",
    "phone": "933 02 31 38",
    "email": "reservas@hotelpeninsular.net",
    "latitude": 41.3795967,
    "longitude": 2.1725011,
    "rooms": []
  },
  {
    "id": 38433,
    "name": "Hotel Palermo Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "3,3",
    "Nº Reviews": 261,
    "Código Plus": "95JF+HJ Barcelona",
    "addres": "Carrer de la Boqueria, 21, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelpalermobarcelona.com",
    "phone": "933 02 40 02",
    "email": "-",
    "latitude": 41.3814939,
    "longitude": 2.1740913,
    "rooms": []
  },
  {
    "id": 38803,
    "name": "Hotel BESTPRICE Diagonal",
    "description": "Hotel de 1 estrella",
    "rating": "4,3",
    "Nº Reviews": 435,
    "Código Plus": "C655+VX Barcelona",
    "addres": "Avinguda Diagonal, 70, 08019 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelesbestprice.com",
    "phone": "935 99 12 71",
    "email": "madrid@hotelesbestprice.com",
    "latitude": 41.4096446,
    "longitude": 2.2099255,
    "rooms": [{
          "id": 18,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 39360,
    "name": "Hotel Trànsit Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "3,8",
    "Nº Reviews": 448,
    "Código Plus": "94HV+76 Barcelona",
    "addres": "Carrer del Rector Triadó, 82, 08014 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hoteltransit.es",
    "phone": "934 24 60 13",
    "email": "leaflet@1.3.1",
    "latitude": 41.3781881,
    "longitude": 2.1430329,
    "rooms": [{
          "id": 19,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 39399,
    "name": "Garden House Hostel Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "4,2",
    "Nº Reviews": 281,
    "Código Plus": "C5P6+9G Barcelona",
    "addres": "Carrer d&apos;Hedilla, 58, 08031 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "feetuphostels.com",
    "phone": "934 27 24 79",
    "email": "-",
    "latitude": 41.4359688,
    "longitude": 2.1612614,
    "rooms": []
  },
  {
    "id": 39661,
    "name": "Hotel Everest",
    "description": "Hotel de 1 estrella",
    "rating": "3,9",
    "Nº Reviews": 161,
    "Código Plus": "C56F+G8 Barcelona",
    "addres": "Travessera de Gràcia, 441, 08025 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hoteleverest.es",
    "phone": "934 36 98 00",
    "email": "8b4e078a51d04e0e9efdf470027f0ec1@sentry.wixpress.com",
    "latitude": 41.4112804,
    "longitude": 2.1732738,
    "rooms": []
  },
  {
    "id": 39665,
    "name": "B&amp;B Barcelona City Seven",
    "description": "Hotel de 1 estrella",
    "rating": "3,4",
    "Nº Reviews": 94,
    "Código Plus": "94WX+X2 Barcelona",
    "addres": "Carrer d&apos;Aribau, 235, 08021 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "barcelonacityseven.com",
    "phone": "934 87 97 62",
    "email": "-",
    "latitude": 41.3974704,
    "longitude": 2.1475225,
    "rooms": [{
          "id": 22,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 39668,
    "name": "Generator Hostels",
    "description": "Hotel de 1 estrella",
    "rating": "4,2",
    "Nº Reviews": 2.235,
    "Código Plus": "95X7+M2 Barcelona",
    "addres": "Carrer de Còrsega, 373, 08037 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "staygenerator.com",
    "phone": "932 20 03 77",
    "email": "-",
    "latitude": 41.3991278,
    "longitude": 2.1625306,
    "rooms": [{
          "id": 23,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 39678,
    "name": "House by Pillow",
    "description": "Hotel de 1 estrella",
    "rating": "4,3",
    "Nº Reviews": 191,
    "Código Plus": "C5CH+9G Barcelona",
    "addres": "Carrer de Rubió i Ors, 3, 08041 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "bypillow.com",
    "phone": "936 67 22 32",
    "email": "ramblas@bypillow.com",
    "latitude": 41.4209175,
    "longitude": 2.1788457,
    "rooms": [{
          "id": 24,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]
  },
  {
    "id": 39685,
    "name": "Barcelona City Street",
    "description": "Hotel de 1 estrella",
    "rating": "3,6",
    "Nº Reviews": 86,
    "Código Plus": "94XX+J7 Barcelona",
    "addres": "Carrer de Dénia, 32, 08006 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "barcelonacitystreet.com",
    "phone": "934 87 97 62",
    "email": "-",
    "latitude": 41.3990245,
    "longitude": 2.1482446,
    "rooms": [{
          "id": 25,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 39689,
    "name": "Primavera-Hostel",
    "description": "Hotel de 1 estrella",
    "rating": "4,6",
    "Nº Reviews": 374,
    "Código Plus": "95X9+7F Barcelona",
    "addres": "Carrer de Mallorca, 330, 08037 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "primavera-hostel.com",
    "phone": "931 75 21 51",
    "email": "-",
    "latitude": 41.3981982,
    "longitude": 2.1687397,
    "rooms": [{
          "id": 26,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 39707,
    "name": "Bedcelona",
    "description": "Hotel de 1 estrella",
    "rating": "3,3",
    "Nº Reviews": 196,
    "Código Plus": "C555+3V Barcelona",
    "addres": "Carrer de la Legalitat, 12, 08024 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "bedcelona.tariffy.com",
    "phone": "651 30 81 89",
    "email": "info@tariffy.com",
    "latitude": 41.4076417,
    "longitude": 2.1597129,
    "rooms": []
  },
  {
    "id": 39710,
    "name": "Jam Hostel Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "4,7",
    "Nº Reviews": 211,
    "Código Plus": "C535+WW Barcelona",
    "addres": "Carrer de Montmany, 38, 42, 08012 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "jamhostelbarcelona.com",
    "phone": "933 15 53 38",
    "email": "info@jamhostelbarcelona.com",
    "latitude": 41.4047637,
    "longitude": 2.1597993,
    "rooms": [{
          "id": 28,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 39737,
    "name": "Travelodge Barcelona Poblenou",
    "description": "Hotel de 1 estrella",
    "rating": "3,8",
    "Nº Reviews": 2.337,
    "Código Plus": "C622+2C Barcelona",
    "addres": "Carrer de Llull, 170, 08005 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "travelodge.es",
    "phone": "936 24 18 02",
    "email": "-",
    "latitude": 41.4,
    "longitude": 2.2011111,
    "rooms": [{
          "id": 29,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 39745,
    "name": "TIBIDABO APARTMENTS (Cad Gispert SL)",
    "description": "Hotel de 1 estrella",
    "rating": "4,2",
    "Nº Reviews": 48,
    "Código Plus": "C4CQ+MJ Barcelona",
    "addres": "Carrer de Jericó, 20, 08035 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "",
    "phone": "677 51 86 08",
    "email": "-",
    "latitude": 41.4216972,
    "longitude": 2.1390417,
    "rooms": []
  },
  {
    "id": 39758,
    "name": "Picasso Suites Barcelona Luxury Apartments",
    "description": "Hotel de 1 estrella",
    "rating": "4,5",
    "Nº Reviews": 61,
    "Código Plus": "95W9+GC Barcelona",
    "addres": "Carrer de València, 334, 08009 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "picassosuites.com",
    "phone": "633 58 30 24",
    "email": "damien@picassosuites.com",
    "latitude": 41.3962877,
    "longitude": 2.168549,
    "rooms": []
  },
  {
    "id": 39763,
    "name": "No Limit Hostel Graffiti",
    "description": "Hotel de 1 estrella",
    "rating": "3,5",
    "Nº Reviews": 296,
    "Código Plus": "C54M+G9 Barcelona",
    "addres": "Carrer d&apos;Aragó, 527, 08026 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "nolimithostels.com",
    "phone": "931 86 33 97",
    "email": "-",
    "latitude": 41.4062889,
    "longitude": 2.1834611,
    "rooms": [{
          "id": 32,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 39767,
    "name": "Diagonal House",
    "description": "Hotel de 1 estrella",
    "rating": "3,6",
    "Nº Reviews": 168,
    "Código Plus": "95W6+WJ Barcelona",
    "addres": "Avinguda Diagonal, 436, 08037 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "",
    "phone": "935 31 32 40",
    "email": "-",
    "latitude": 41.3972637,
    "longitude": 2.1615352,
    "rooms": [{
          "id": 33,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 39778,
    "name": "Hotel Poblenou B&amp;B",
    "description": "Hotel de 1 estrella",
    "rating": "4,6",
    "Nº Reviews": 82,
    "Código Plus": "96X3+8P Barcelona",
    "addres": "Carrer del Taulat, 30, 08005 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalpoblenou.com",
    "phone": "932 21 26 01",
    "email": "info@hostalpoblenou.com",
    "latitude": 41.3983007,
    "longitude": 2.2043691,
    "rooms": []
  },
  {
    "id": 39782,
    "name": "ALBERGUE STUDIO HOSTEL",
    "description": "Hotel de 1 estrella",
    "rating": "4,1",
    "Nº Reviews": 217,
    "Código Plus": "94X9+XG Barcelona",
    "addres": "Carrer de la Duquessa d&apos;Orleans, 56, 08034 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "alberguestudio.com",
    "phone": "932 05 09 61",
    "email": "info@alberguestudio.com",
    "latitude": 41.3999238,
    "longitude": 2.1187623,
    "rooms": [{
          "id": 35,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 39783,
    "name": "Pensión Alberdi",
    "description": "Hotel de 1 estrella",
    "rating": "2,3",
    "Nº Reviews": 117,
    "Código Plus": "C524+QW Barcelona",
    "addres": "Carrer del Torrent de l&apos;Olla, 95, 08012 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "",
    "phone": "932 18 85 73",
    "email": "-",
    "latitude": 41.401915,
    "longitude": 2.157357,
    "rooms": [{
          "id": 36,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 39844,
    "name": "Hotel Curious",
    "description": "Hotel de 1 estrella",
    "rating": "4,3",
    "Nº Reviews": 228,
    "Código Plus": "95JC+W5 Barcelona",
    "addres": "Carrer del Carme, 25, 08001 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelcurious.com",
    "phone": "933 01 44 84",
    "email": "hotel@hotelcurious.com",
    "latitude": 41.3823175,
    "longitude": 2.1704775,
    "rooms": []
  },
  {
    "id": 39845,
    "name": "Hotel Aneto",
    "description": "Hotel de 1 estrella",
    "rating": "3,8",
    "Nº Reviews": 283,
    "Código Plus": "95J9+RV Barcelona",
    "addres": "Carrer del Carme, 38, 08001 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelaneto.com",
    "phone": "933 01 99 89",
    "email": "aneto@hotelaneto.com",
    "latitude": 41.3820818,
    "longitude": 2.1696779,
    "rooms": [{
          "id": 38,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 39863,
    "name": "Hotel Brick Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "4,4",
    "Nº Reviews": 40,
    "Código Plus": "94CW+XF Barcelona",
    "addres": "C, Gran Via de les Corts Catalanes, 304, 08004 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotel-brickbarcelona.com",
    "phone": "934 23 64 17",
    "email": "recepcion@hotel-brickbarcelona.com",
    "latitude": 41.3724589,
    "longitude": 2.1461823,
    "rooms": [{
          "id": 39,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40035,
    "name": "Yellow Nest Hostel Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "4,1",
    "Nº Reviews": 369,
    "Código Plus": "94GF+VG Barcelona",
    "addres": "Passatge del Regent Mendieta, 5, 08028 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "feetuphostels.com",
    "phone": "934 49 05 96",
    "email": "-",
    "latitude": 41.3771911,
    "longitude": 2.1238724,
    "rooms": []
  },
  {
    "id": 40067,
    "name": "Alberg Pere Tarrés Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "3,7",
    "Nº Reviews": 944,
    "Código Plus": "94QM+5F Barcelona",
    "addres": "Carrer de Numància, 151, 08029 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "peretarres.org",
    "phone": "934 10 23 09",
    "email": "fundacio@peretarres.org",
    "latitude": 41.3879394,
    "longitude": 2.133708,
    "rooms": []
  },
  {
    "id": 40083,
    "name": "Free Hostels Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "4,4",
    "Nº Reviews": 285,
    "Código Plus": "94QV+CQ Barcelona",
    "addres": "Carrer de Londres, 20, 08029 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "free-hostels.com",
    "phone": "933 15 47 09",
    "email": "info.barcelona@free-hostels.com",
    "latitude": 41.3885969,
    "longitude": 2.1444804,
    "rooms": [{
          "id": 42,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40091,
    "name": "Hostelscat BCN",
    "description": "Hotel de 1 estrella",
    "rating": "3,3",
    "Nº Reviews": 129,
    "Código Plus": "94GM+C8 Barcelona",
    "addres": "Carrer de Panissars, 5, 08028 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostelscat.eshotel.site",
    "phone": "936 67 27 06",
    "email": "-",
    "latitude": 41.376023,
    "longitude": 2.1333652,
    "rooms": [{
          "id": 43,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40101,
    "name": "Residencia Universitaria Sants",
    "description": "Hotel de 1 estrella",
    "rating": "3,6",
    "Nº Reviews": 79,
    "Código Plus": "94JM+44 Barcelona",
    "addres": "Carrer de Joan Güell, 86, 88, 08028 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "residenciasants.com",
    "phone": "934 09 40 27",
    "email": "info@residenciasants.com",
    "latitude": 41.3803038,
    "longitude": 2.1328162,
    "rooms": []
  },
  {
    "id": 40118,
    "name": "Hostal Conde Güell",
    "description": "Hotel de 1 estrella",
    "rating": "4,0",
    "Nº Reviews": 228,
    "Código Plus": "94GF+X3 Barcelona",
    "addres": "Carrer del Comte de Güell, 34, 08028 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalcondeguell.com",
    "phone": "934 40 02 57",
    "email": "info@hostalcondeguell.com",
    "latitude": 41.377448,
    "longitude": 2.1226761,
    "rooms": []
  },
  {
    "id": 40143,
    "name": "My Home in Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "4,8",
    "Nº Reviews": 4,
    "Código Plus": "94FQ+82 Barcelona",
    "addres": "Carrer de Rossend Arús, 19, 08014 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "",
    "phone": "605 56 81 68",
    "email": "-",
    "latitude": 41.3732788,
    "longitude": 2.1375971,
    "rooms": []
  },
  {
    "id": 40202,
    "name": "Hostal Valls",
    "description": "Hotel de 1 estrella",
    "rating": "4,2",
    "Nº Reviews": 103,
    "Código Plus": "94WW+WJ Barcelona",
    "addres": "Carrer de Laforja, 82, 08021 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "",
    "phone": "932 09 69 97",
    "email": "-",
    "latitude": 41.3972776,
    "longitude": 2.1466031,
    "rooms": [{
          "id": 47,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40680,
    "name": "Buba House",
    "description": "Hotel de 1 estrella",
    "rating": "3,9",
    "Nº Reviews": 273,
    "Código Plus": "95R6+6X Barcelona",
    "addres": "Carrer d&apos;Aragó, 239, 08007 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "",
    "phone": "935 00 83 18",
    "email": "-",
    "latitude": 41.3906139,
    "longitude": 2.1624333,
    "rooms": [{
          "id": 48,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "95",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40695,
    "name": "Hotel Coronado",
    "description": "Hotel de 1 estrella",
    "rating": "3,3",
    "Nº Reviews": 482,
    "Código Plus": "95F9+97 Barcelona",
    "addres": "Carrer Nou de la Rambla, 134, 08004 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelcoronado.net",
    "phone": "934 42 34 48",
    "email": "-",
    "latitude": 41.373385,
    "longitude": 2.1682334,
    "rooms": []
  },
  {
    "id": 40706,
    "name": "Casa Kessler Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "4,5",
    "Nº Reviews": 299,
    "Código Plus": "95R5+5P Barcelona",
    "addres": "Carrer d&apos;Enric Granados, 30, 08008 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "casakesslerbarcelona.com",
    "phone": "935 28 57 42",
    "email": "info@casakesslerbarcelona.com",
    "latitude": 41.3904228,
    "longitude": 2.1592913,
    "rooms": []
  },
  {
    "id": 40707,
    "name": "St Christopher&apos;s Inn | Hostel in Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "4,2",
    "Nº Reviews": 1.803,
    "Código Plus": "95P9+C3 Barcelona",
    "addres": "Carrer de Bergara, 3, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "st-christophers.co.uk",
    "phone": "931 75 14 01",
    "email": "feedback@st-christophers.co.uk",
    "latitude": 41.3860993,
    "longitude": 2.167679,
    "rooms": []
  },
  {
    "id": 40712,
    "name": "Hotel Jaume I",
    "description": "Hotel de 1 estrella",
    "rating": "3,5",
    "Nº Reviews": 361,
    "Código Plus": "95MH+85 Barcelona",
    "addres": "Carrer de Jaume I, 11, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hoteljaumei.cat",
    "phone": "932 69 30 74",
    "email": "-",
    "latitude": 41.3833363,
    "longitude": 2.1778807,
    "rooms": [{
          "id": 52,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40713,
    "name": "Black Swan Hostel",
    "description": "Hotel de 1 estrella",
    "rating": "4,3",
    "Nº Reviews": 434,
    "Código Plus": "95RH+F2 Barcelona",
    "addres": "Carrer d&apos;Alí Bei, 15, 08010 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "blackswanhostel.com",
    "phone": "932 31 13 69",
    "email": "barcelona@blackswanhostel.com",
    "latitude": 41.3912361,
    "longitude": 2.1775861,
    "rooms": [{
          "id": 53,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "95",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40719,
    "name": "Hostal Barcelona Ramblas",
    "description": "Hotel de 1 estrella",
    "rating": "3,6",
    "Nº Reviews": 117,
    "Código Plus": "95HC+2X Barcelona",
    "addres": "Carrer Nou de la Rambla, 50, 08001 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "behostels.com",
    "phone": "934 42 36 69",
    "email": "groups@behostels.com",
    "latitude": 41.3775059,
    "longitude": 2.1724691,
    "rooms": []
  },
  {
    "id": 40748,
    "name": "Camino Bnb",
    "description": "Hotel de 1 estrella",
    "rating": "4,6",
    "Nº Reviews": 109,
    "Código Plus": "95C6+R3 Barcelona",
    "addres": "Carrer de la Palma, 24, 08004 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "caminobnb.com",
    "phone": "933 48 81 72",
    "email": "-",
    "latitude": 41.372067,
    "longitude": 2.160154,
    "rooms": [{
          "id": 55,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,          
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40760,
    "name": "Hostal Nuevo Colón",
    "description": "Hotel de 1 estrella",
    "rating": "3,8",
    "Nº Reviews": 321,
    "Código Plus": "95PP+22 Barcelona",
    "addres": "Av. del Marquès de l&apos;Argentera, 19, 08003 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalnuevocolon.com",
    "phone": "933 19 50 77",
    "email": "-",
    "latitude": 41.3850018,
    "longitude": 2.1850407,
    "rooms": [{
          "id": 56,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40761,
    "name": "El Cantón Hotel",
    "description": "Hotel de 1 estrella",
    "rating": "4,0",
    "Nº Reviews": 398,
    "Código Plus": "95HH+96 Barcelona",
    "addres": "Carrer Nou de Sant Francesc, 40, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelcanton-bcn.com",
    "phone": "933 17 30 19",
    "email": "info@hotelcanton-bcn.com",
    "latitude": 41.3784966,
    "longitude": 2.1780209,
    "rooms": []
  },
  {
    "id": 40764,
    "name": "The Hostel Box Port",
    "description": "Hotel de 1 estrella",
    "rating": "4,7",
    "Nº Reviews": 220,
    "Código Plus": "95FF+GM Barcelona",
    "addres": "Carrer d&apos;Albareda, 6, 08004 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostelone.com",
    "phone": "934 43 13 10",
    "email": "hipstel@onehostel.com",
    "latitude": 41.3737709,
    "longitude": 2.1742175,
    "rooms": [{
          "id": 58,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40766,
    "name": "Hostal Paraiso",
    "description": "Hotel de 1 estrella",
    "rating": "3,7",
    "Nº Reviews": 329,
    "Código Plus": "95G7+XP Barcelona",
    "addres": "Ronda de Sant Pau, 55, 57, 08015 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostal-paraiso.negocio.site",
    "phone": "933 29 93 78",
    "email": "-",
    "latitude": 41.3773804,
    "longitude": 2.1643467,
    "rooms": [{
          "id": 59,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40770,
    "name": "LENIN HOSTEL",
    "description": "Hotel de 1 estrella",
    "rating": "3,8",
    "Nº Reviews": 402,
    "Código Plus": "95V7+9R Barcelona",
    "addres": "Carrer de València, 278, 08007 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "leninhostel.com",
    "phone": "639 30 72 02",
    "email": "-",
    "latitude": 41.3934535,
    "longitude": 2.1645058,
    "rooms": []
  },
  {
    "id": 40774,
    "name": "Mediterranean Youth Hostel",
    "description": "Hotel de 1 estrella",
    "rating": "4,4",
    "Nº Reviews": 300,
    "Código Plus": "95VC+QW Barcelona",
    "addres": "Carrer de la Diputació, 335, 08009 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "mediterraneanhostel.com",
    "phone": "932 44 02 78",
    "email": "-",
    "latitude": 41.3945,
    "longitude": 2.1723333,
    "rooms": []
  },
  {
    "id": 40775,
    "name": "Hostel New York",
    "description": "Hotel de 1 estrella",
    "rating": "3,6",
    "Nº Reviews": 316,
    "Código Plus": "95JH+6R Barcelona",
    "addres": "Carrer d&apos;en Gignàs, 6, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "bcnalberg.com",
    "phone": "933 15 03 04",
    "email": "info@hostelnybcn.com",
    "latitude": 41.3805796,
    "longitude": 2.1795799,
    "rooms": [{
          "id": 62,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40782,
    "name": "Hostal Europa",
    "description": "Hotel de 1 estrella",
    "rating": "3,5",
    "Nº Reviews": 446,
    "Código Plus": "95JF+JQ Barcelona",
    "addres": "Carrer de la Boqueria, 18, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalresidenciaeuropa.com",
    "phone": "933 18 76 20",
    "email": "hostalresidenciaeuropa@hotmail.com",
    "latitude": 41.3815193,
    "longitude": 2.1744311,
    "rooms": [{
          "id": 63,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40784,
    "name": "Sun &amp; Moon hostel",
    "description": "Hotel de 1 estrella",
    "rating": "3,6",
    "Nº Reviews": 136,
    "Código Plus": "95JF+CX Barcelona",
    "addres": "Carrer de Ferran, 17, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "smhostel.net",
    "phone": "932 70 20 60",
    "email": "-",
    "latitude": 41.381015,
    "longitude": 2.1749227,
    "rooms": []
  },
  {
    "id": 40786,
    "name": "Be Ramblas Guest House",
    "description": "Hotel de 1 estrella",
    "rating": "3,7",
    "Nº Reviews": 122,
    "Código Plus": "95HF+22 Barcelona",
    "addres": "Carrer Nou de la Rambla, 50, 08001 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "beramblasguesthouse.com",
    "phone": "",
    "email": "-",
    "latitude": 41.3775259,
    "longitude": 2.1725278,
    "rooms": [{
          "id": 65,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40794,
    "name": "Hostal Elkano",
    "description": "Hotel de 1 estrella",
    "rating": "3,6",
    "Nº Reviews": 298,
    "Código Plus": "95F6+J3 Barcelona",
    "addres": "Carrer d&apos;Elkano, 78, 08004 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalelkano.com",
    "phone": "933 29 92 50",
    "email": "info@hostalelkano.com",
    "latitude": 41.3740854,
    "longitude": 2.1602378,
    "rooms": [{
          "id": 66,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40797,
    "name": "Pensión Ciudadela",
    "description": "Hotel de 1 estrella",
    "rating": "4,1",
    "Nº Reviews": 241,
    "Código Plus": "95MM+VV Barcelona",
    "addres": "Carrer del Comerç, 33, 08003 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "pensionciudadela.com",
    "phone": "933 19 62 03",
    "email": "info@pensionciudadela.com",
    "latitude": 41.384736,
    "longitude": 2.184704,
    "rooms": []
  },
  {
    "id": 40803,
    "name": "Bird House",
    "description": "Hotel de 1 estrella",
    "rating": "4,1",
    "Nº Reviews": 367,
    "Código Plus": "95J5+MJ Barcelona",
    "addres": "Carrer del Comte d&apos;Urgell, 51 bis, 1 planta, 08011 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "birdhouse.es",
    "phone": "616 46 66 84",
    "email": "reception@birdhouse.es",
    "latitude": 41.381671,
    "longitude": 2.159049,
    "rooms": [{
          "id": 68,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40804,
    "name": "HelloBCN Hostel",
    "description": "Hotel de 1 estrella",
    "rating": "4,2",
    "Nº Reviews": 587,
    "Código Plus": "95F9+CM Barcelona",
    "addres": "Carrer de Lafont, 8, 10, 08004 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hellobcnhostel.com",
    "phone": "934 42 83 92",
    "email": "info@hellobcnhostel.com",
    "latitude": 41.3736013,
    "longitude": 2.1691306,
    "rooms": [{
          "id": 69,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40807,
    "name": "Hostal Nitzs Bcn",
    "description": "Hotel de 1 estrella",
    "rating": "3,8",
    "Nº Reviews": 148,
    "Código Plus": "95JH+JF Barcelona",
    "addres": "Carrer de Calella, 1, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalnitzsbcn.com",
    "phone": "933 02 11 05",
    "email": "-",
    "latitude": 41.3815722,
    "longitude": 2.1786417,
    "rooms": [{
          "id": 70,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40808,
    "name": "Pension Francia",
    "description": "Hotel de 1 estrella",
    "rating": "3,1",
    "Nº Reviews": 234,
    "Código Plus": "95MM+FC Barcelona",
    "addres": "Carrer de Rera Palau, 4, 08003 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "pensionfrancia.com",
    "phone": "933 19 03 76",
    "email": "-",
    "latitude": 41.3836412,
    "longitude": 2.1836184,
    "rooms": [{
          "id": 71,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40810,
    "name": "Hostal San Ramón",
    "description": "Hotel de 1 estrella",
    "rating": "2,7",
    "Nº Reviews": 214,
    "Código Plus": "95HC+4Q Barcelona",
    "addres": "Carrer de Sant Ramon, 15, 08001 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "pensionsanramon.com",
    "phone": "933 29 60 22",
    "email": "info@pensionsanramon.com",
    "latitude": 41.3778597,
    "longitude": 2.1719064,
    "rooms": []
  },
  {
    "id": 40811,
    "name": "Pensión Casa de Barca",
    "description": "Hotel de 1 estrella",
    "rating": "3,8",
    "Nº Reviews": 38,
    "Código Plus": "95RG+9J Barcelona",
    "addres": "Carrer de Girona, 4, 3-2, 08010 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "casadebarca.com",
    "phone": "932 32 51 02",
    "email": "-",
    "latitude": 41.3909312,
    "longitude": 2.1765047,
    "rooms": [{
          "id": 73,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40813,
    "name": "Hostal Baires",
    "description": "Hotel de 1 estrella",
    "rating": "2,8",
    "Nº Reviews": 194,
    "Código Plus": "95JH+4J Barcelona",
    "addres": "Carrer d&apos;Avinyó, 37, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalbaires.com",
    "phone": "933 19 77 74",
    "email": "info@hostalbaires.com",
    "latitude": 41.3803361,
    "longitude": 2.1791139,
    "rooms": [{
          "id": 74,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40814,
    "name": "Pensión Mariluz",
    "description": "Hotel de 1 estrella",
    "rating": "4,2",
    "Nº Reviews": 108,
    "Código Plus": "95JH+F4 Barcelona",
    "addres": "Carrer del Palau, 4, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "pensionmariluz.com",
    "phone": "933 17 34 63",
    "email": "info@pensionmariluz.com",
    "latitude": 41.3811967,
    "longitude": 2.1777819,
    "rooms": []
  },
  {
    "id": 40816,
    "name": "Pensió Portugal",
    "description": "Hotel de 1 estrella",
    "rating": "3,8",
    "Nº Reviews": 291,
    "Código Plus": "95HH+66 Barcelona",
    "addres": "Carrer de Josep Anselm Clavé, 27, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "pensionportugal.com",
    "phone": "933 42 60 61",
    "email": "hostalportugal@hotmail.com",
    "latitude": 41.3780148,
    "longitude": 2.1780506,
    "rooms": []
  },
  {
    "id": 40832,
    "name": "Hotel Restaurante La Ciudadela",
    "description": "Hotel de 1 estrella",
    "rating": "4,2",
    "Nº Reviews": 1.022,
    "Código Plus": "95QM+QF Barcelona",
    "addres": "Passeig de Lluís Companys, 2, 08018 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "ciudadelaparc.com",
    "phone": "933 09 95 57",
    "email": "-",
    "latitude": 41.3894001,
    "longitude": 2.1837235,
    "rooms": [{
          "id": 77,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 40837,
    "name": "Pensión Palacio",
    "description": "Hotel de 1 estrella",
    "rating": "3,5",
    "Nº Reviews": 117,
    "Código Plus": "95JM+Q6 Barcelona",
    "addres": "Passeig d&apos;Isabel II, 10, 08003 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "",
    "phone": "933 19 36 09",
    "email": "-",
    "latitude": 41.3819444,
    "longitude": 2.1830556,
    "rooms": [{
          "id": 78,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 40838,
    "name": "Pensión Peiró",
    "description": "Hotel de 1 estrella",
    "rating": "4,2",
    "Nº Reviews": 93,
    "Código Plus": "95F9+FR Barcelona",
    "addres": "Carrer de Lafont, 1, 3, 08004 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "pension-peiro.com",
    "phone": "933 29 89 91",
    "email": "-",
    "latitude": 41.3737332,
    "longitude": 2.1695558,
    "rooms": []
  },
  {
    "id": 41041,
    "name": "Hotel Urquinaona Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "3,1",
    "Nº Reviews": 265,
    "Código Plus": "95QF+PM Barcelona",
    "addres": "Ronda de Sant Pere, 24, 08010 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelurquinaona.com",
    "phone": "932 68 13 36",
    "email": "urquinaona@barcelonahotel.com",
    "latitude": 41.3892624,
    "longitude": 2.1741849,
    "rooms": [{
          "id": 80,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 41062,
    "name": "Hostal Levante",
    "description": "Hotel de 1 estrella",
    "rating": "3,8",
    "Nº Reviews": 426,
    "Código Plus": "95JG+HM Barcelona",
    "addres": "Baixada de Sant Miquel, 2, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostallevante.com",
    "phone": "933 17 95 65",
    "email": "-",
    "latitude": 41.3814044,
    "longitude": 2.1766757,
    "rooms": [{
          "id": 81,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 41063,
    "name": "BruStar Gotic",
    "description": "Hotel de 1 estrella",
    "rating": "3,1",
    "Nº Reviews": 79,
    "Código Plus": "95RH+MJ Barcelona",
    "addres": "Ronda de Sant Pere, 53, 08010 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalbrustargotic.com",
    "phone": "932 45 78 44",
    "email": "-",
    "latitude": 41.3916303,
    "longitude": 2.1790678,
    "rooms": []
  },
  {
    "id": 41077,
    "name": "Hostal Fina",
    "description": "Hotel de 1 estrella",
    "rating": "4,0",
    "Nº Reviews": 193,
    "Código Plus": "95MF+C2 Barcelona",
    "addres": "Carrer de la Portaferrissa, 11, 08002 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalfina.com",
    "phone": "933 17 97 87",
    "email": "info@hostalfina.com",
    "latitude": 41.3835353,
    "longitude": 2.1725667,
    "rooms": []
  },
  {
    "id": 41078,
    "name": "Hostal River",
    "description": "Hotel de 1 estrella",
    "rating": "3,8",
    "Nº Reviews": 210,
    "Código Plus": "95HF+R3 Barcelona",
    "addres": "Carrer de Sant Pau, 15, 08001 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hostalriver.com",
    "phone": "933 18 94 93",
    "email": "hostalriverramblas@yahoo.es",
    "latitude": 41.3795547,
    "longitude": 2.1727171,
    "rooms": [{
          "id": 84,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 41332,
    "name": "Hotel BESTPRICE Gracia",
    "description": "Hotel de 1 estrella",
    "rating": "4,5",
    "Nº Reviews": 398,
    "Código Plus": "C556+V8 Barcelona",
    "addres": "Carrer de Martí, 124, 08024 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "hotelesbestprice.com",
    "phone": "934 61 42 60",
    "email": "madrid@hotelesbestprice.com",
    "latitude": 41.409699,
    "longitude": 2.1608354,
    "rooms": [{
          "id": 85,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 41368,
    "name": "Suite Home Barcelona",
    "description": "Hotel de 1 estrella",
    "rating": "4,0",
    "Nº Reviews": 41,
    "Código Plus": "C54F+MR Barcelona",
    "addres": "Avinguda de Gaudí, 28, 08025 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "suitehomebarcelona.com",
    "phone": "931 76 20 39",
    "email": "-",
    "latitude": 41.4066309,
    "longitude": 2.1745744,
    "rooms": []
  },
  {
    "id": 41377,
    "name": "Hostal Barcelona Rooms 294",
    "description": "Hotel de 1 estrella",
    "rating": "3,7",
    "Nº Reviews": 58,
    "Código Plus": "C538+GF Barcelona",
    "addres": "Carrer de Roger de Flor, 294, 08025 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "barcelonarooms294.com",
    "phone": "680 62 42 06",
    "email": "booking@barcelonarooms294.com",
    "latitude": 41.4038739,
    "longitude": 2.1661618,
    "rooms": [{
          "id": 87,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
  {
    "id": 41378,
    "name": "Heart of Gràcia",
    "description": "Hotel de 1 estrella",
    "rating": "4,5",
    "Nº Reviews": 4,
    "Código Plus": "C533+XG Barcelona",
    "addres": "Carrer de Santa Àgata, 38, 08012 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "heartofgraciabarcelona.com.es",
    "phone": "",
    "email": "-",
    "latitude": 41.4049948,
    "longitude": 2.1538437,
    "rooms": [{
          "id": 88,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "75",
          "onSale": 1,
          "price": "95.00",
          "type": "Cama Sencilla",
          "image1": "https://www.cataloniahotels.com/es/blog/wp-content/uploads/2024/01/tipos-habitaciones-hotel.jpg",
        }]

  },
  {
    "id": 41391,
    "name": "Hostel St.Marius-Gracia",
    "description": "Hotel de 1 estrella",
    "rating": "4,0",
    "Nº Reviews": 2,
    "Código Plus": "C523+J8 Barcelona",
    "addres": "08012 Barcelona",
    "city": "Barcelona",
    "province": "Barcelona",
    "website": "",
    "phone": "607 92 79 37",
    "email": "-",
    "latitude": 41.4015397,
    "longitude": 2.1533345,
    "rooms": [{
          "id": 89,
          "name": "",
          "details": "",
          "number": "",
          "availability": 1,
          "capacity": 0,
          "offerPrice": "110",
          "onSale": 1,
          "price": "130.00",
          "type": "Cama Doble",
          "image1": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2014/10/13/14131900739336.jpg",
        }]
  },
];